import type { EditorTheme } from "./CodeEditor";

export const editorFont =
  "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";

export const graphiteTheme: EditorTheme = {
  name: "leetrace-graphite",
  data: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "dcdce0" },
      { token: "keyword", foreground: "a5a6fb" },
      { token: "string", foreground: "8fcfa0" },
      { token: "string.escape", foreground: "8fcfa0" },
      { token: "number", foreground: "e8b56d" },
      { token: "number.hex", foreground: "e8b56d" },
      { token: "comment", foreground: "5f5f6a", fontStyle: "italic" },
      { token: "identifier", foreground: "dcdce0" },
      { token: "delimiter", foreground: "85858f" },
      { token: "delimiter.bracket", foreground: "a1a1aa" },
      { token: "delimiter.parenthesis", foreground: "a1a1aa" },
      { token: "tag", foreground: "c4b5fd" },
      { token: "type", foreground: "c4b5fd" },
    ],
    colors: {
      "editor.background": "#0f0f12",
      "editor.foreground": "#dcdce0",
      "editorGutter.background": "#0f0f12",
      "editorLineNumber.foreground": "#3a3a43",
      "editorLineNumber.activeForeground": "#a1a1aa",
      "editor.lineHighlightBackground": "#ffffff07",
      "editor.lineHighlightBorder": "#00000000",
      "editorCursor.foreground": "#a5a6fb",
      "editor.selectionBackground": "#6e6ef645",
      "editor.inactiveSelectionBackground": "#6e6ef622",
      "editor.selectionHighlightBackground": "#6e6ef61c",
      "editor.wordHighlightBackground": "#6e6ef618",
      "editor.findMatchBackground": "#fbbf2440",
      "editor.findMatchHighlightBackground": "#fbbf241f",
      "editorIndentGuide.background1": "#1d1d22",
      "editorIndentGuide.activeBackground1": "#33333b",
      "editorWhitespace.foreground": "#2e2e35",
      "editorBracketMatch.background": "#6e6ef620",
      "editorBracketMatch.border": "#6e6ef655",
      "editorBracketHighlight.foreground1": "#a1a1aa",
      "editorBracketHighlight.foreground2": "#a5a6fb",
      "editorBracketHighlight.foreground3": "#8fcfa0",
      "editorBracketHighlight.foreground4": "#e8b56d",
      "editorBracketHighlight.unexpectedBracket.foreground": "#fb7185",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#ffffff12",
      "scrollbarSlider.hoverBackground": "#ffffff20",
      "scrollbarSlider.activeBackground": "#ffffff2c",
      "editorWidget.background": "#151519",
      "editorWidget.border": "#2e2e35",
      "editorSuggestWidget.background": "#151519",
      "editorSuggestWidget.border": "#2e2e35",
      "editorSuggestWidget.foreground": "#dcdce0",
      "editorSuggestWidget.selectedBackground": "#22222a",
      "editorSuggestWidget.highlightForeground": "#a5a6fb",
      "editorHoverWidget.background": "#151519",
      "editorHoverWidget.border": "#2e2e35",
      "input.background": "#0b0b0e",
      "input.border": "#2e2e35",
      focusBorder: "#8b8cf866",
      "widget.shadow": "#00000080",
    },
  },
};
